### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by Derpolino** [youngesbill/snapchatAPI#2]
Traceback (most recent call last):
  File "H:\Desktop\Mes_codes\Python\snapchat\snapchatAPI\test.py", line 3, in <module>
    acc.login()
  File "H:\Desktop\Mes_codes\Python\snapchat\snapchatAPI\Snapchat.py", line 249, in login
    r = self.request("/loq/login", data = data)
  File "H:\Desktop\Mes_codes\Python\snapchat\snapchatAPI\Snapchat.py", line 95, in request
    r_tokens = self.QueryTools.get_tokens(endpoint, auth_token=auth_token)
  File "H:\Desktop\Mes_codes\Python\snapchat\snapchatAPI\QueryTools.py", line 45, in get_tokens
    dataEncoded = self.encryption(json.dumps(dataJson))
  File "H:\Desktop\Mes_codes\Python\snapchat\snapchatAPI\QueryTools.py", line 31, in encryption
    return b64encode(Crypto.Cipher.AES.new(self.privateKey, Crypto.Cipher.AES.MODE_CBC, "\x00" \* 16).encrypt(padded.encode('utf8')))
  File "C:\Python27\lib\site-packages\Crypto\Cipher\AES.py", line 95, in new
    return AESCipher(key, _args, *_kwargs)
  File "C:\Python27\lib\site-packages\Crypto\Cipher\AES.py", line 59, in **init**
    blockalgo.BlockAlgo.**init**(self, _AES, key, _args, *_kwargs)
  File "C:\Python27\lib\site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, _args, *_kwargs)
ValueError: AES key must be either 16, 24, or 32 bytes long

**Comment by youngesbill** [comment]
send email

**Comment by shaunm** [comment]
I have the same issue.
