### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Flabian** [youngesbill/snapchatAPI#3]
I deleted everything from test.py and left only this line : "from Snapchat import Snapchat"

When I try to run it I'm getting this error : 

Traceback (most recent call last):
  File "C:\Users\Flabi\Desktop\snapchatAPI-master\test.py", line 1, in <module>
    from Snapchat import Snapchat
  File "C:\Users\Flabi\Desktop\snapchatAPI-master\Snapchat.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by Derpolino** [comment]
pip install requests

;)

**Comment by Flabian** [comment]
Got it. Now after I installed everything I got another problem. 

> ```
> self._cipher = factory.new(key, *args, **kwargs)
> ```
> 
> ValueError: AES key must be either 16, 24, or 32 bytes long

This appears on the acc.login() line
